# Generated by Django 3.0.2 on 2020-03-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200317_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.CharField(default=None, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jobdescription',
            field=models.CharField(default=None, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='positiondescription',
            field=models.CharField(default=None, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
