# Generated by Django 3.0.3 on 2020-03-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200317_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
