# Generated by Django 3.0.2 on 2020-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=255)),
                ('bookgenres', models.CharField(max_length=500)),
                ('bookauthor', models.CharField(max_length=200)),
                ('bookdesc', models.CharField(max_length=5500)),
            ],
        ),
    ]
