# Generated by Django 3.0.2 on 2020-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='bookimage',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
