# Generated by Django 3.0.3 on 2020-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_interest_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
